version: '3.8'

services:
  demo_daisy_web:
    container_name: demo_daisy_web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "4090:8000"
    networks:
      - demo_daisy

networks:
  demo_daisy:
    driver: demo_daisy
